#!/usr/bin/env python3
"""Check an mr_BP_comod run for a two-cell complex against the sphere's E2 page.

For a cofiber sequence  S^d --f--> S^0 --> C_f  with f detected by a class
x in Ext^{s0, s0+d}_{BP_*BP}(BP_*, BP_*), the short exact sequence of
comodules

    0 --> BP_*  -->  BP_*(C_f)  -->  Sigma^{d+1} BP_*  --> 0

is split over BP_* (both cells are free), so applying Ext gives a long exact
sequence -- and its connecting map is the Yoneda product with the extension
class of that sequence, which is x itself.  Bidegree by bidegree, indexing
classes by (stem, filtration) = (t-s, s),

    0 --> coker(x . - into (n,s)) --> E2(C_f)(n,s)
      --> ker(x . - out of (n-d-1,s)) --> 0.

See docs/SES_CHECK.md for the derivation, and in particular for why the
*non-split* comodule structure of BP_*(C_f) is carried entirely by that
connecting map.

This script evaluates the right-hand side from a *sphere* run and compares it
with the observed left-hand side from a comodule run:

    ./BPtab 35
    ./mr_BP_comod 35 12 sphere
    ./mr_BP_comod 35 12 alpha_1
    ./ses_check.py 35 -c alpha_1

Nothing is recomputed: the inputs are the text tables mr_BP/mr_BP_comod
already write.  Exit status is 1 if any bidegree disagrees.

What is being counted
---------------------
The tables list an F_3-basis of the algebraic Novikov E_infinity page, i.e.
of gr Ext_{BP_*BP} -- v0-towers included, differential-killed classes
excluded.  So the number of surviving classes in a bidegree is the F_3-length
of Ext there: 12 classes in (0,0) is Z_(3) seen through 12 filtration steps,
and the 2 classes in stem 11 are the Z/9 generated by alpha_{3/2}.  Lengths
are additive along a short exact sequence, which is what gets checked.

Ranks are intervals, not guesses
--------------------------------
The multiplication table is pruned by homological degree
(multiplication.cpp:169), so some classes have no line in it.  Rather than
assume such a product vanishes, each rank is bracketed:

    lo = rank of the columns the table does state
    hi = min(lo + #unstated columns, #source classes, #target classes)

and the prediction is reported as the resulting interval.  A bidegree counts
as agreeing when the observed length lies in it, and the check is sharp
exactly when lo = hi -- which it usually is, because the target bidegree is
small or empty.

Other limitations -- read these before believing a mismatch
-----------------------------------------------------------
  * The multiplication tables record only the *leading term* of a product
    with respect to the algebraic Novikov filtration
    (multiplication.cpp:170-172 prints multiplied_names.second and drops
    .first).  A product that jumps filtration is invisible here, which would
    understate a rank and so overstate the prediction.
  * Near the top of the range classes are missing because of the degree
    bound, not because they are absent (docs/CHARTS.md section 6), so
    bidegrees with t = n + s > --max-t are skipped.  The default is the
    largest internal degree t that actually occurs in the sphere run, which
    is where its own data stops being trustworthy.
"""

import argparse
import os
import sys
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from anss_chart import parse_table, MULT_RE  # same table format, one parser

P = 3


# ---------------------------------------------------------------- parsing

def surviving(classes):
    """(stem, s) -> sorted names of the classes surviving the algebraic Novikov SS."""
    cells = defaultdict(list)
    for c in classes.values():
        if not c['killed']:
            cells[(c['stem'], c['s'])].append(c['name'])
    for names in cells.values():
        names.sort()
    return cells


def parse_mult_coeffs(path):
    """source -> Counter(target -> coefficient mod p), or None if absent.

    A repeated target is a coefficient: "x -> y+y+o" means 2y.  Sources with
    no line in the file are *unstated*, not zero, so only what the file
    actually says is returned; the caller keeps the distinction.
    """
    if not os.path.exists(path):
        return None
    products = {}
    with open(path) as fh:
        for line in fh:
            m = MULT_RE.match(line.rstrip('\n'))
            if not m:
                continue
            counts = Counter(t for t in m['targets'].split('+') if t)
            products[m['src']] = Counter({k: v % P for k, v in counts.items()
                                          if v % P})
    return products


# ------------------------------------------------------------ linear algebra

def f3_rank(columns, rows):
    """Rank over F_3 of the matrix whose columns are dicts row_name -> coeff."""
    index = {r: i for i, r in enumerate(rows)}
    mat = []
    for col in columns:
        vec = [0] * len(rows)
        for name, coeff in col.items():
            vec[index[name]] = coeff % P
        mat.append(vec)

    rank = 0
    used = [False] * len(mat)
    for r in range(len(rows)):
        pivot = next((j for j in range(len(mat))
                      if not used[j] and mat[j][r] % P), None)
        if pivot is None:
            continue
        used[pivot] = True
        rank += 1
        inv = pow(mat[pivot][r], P - 2, P)          # 1/a in F_3
        for j in range(len(mat)):
            if j != pivot and mat[j][r] % P:
                factor = (mat[j][r] * inv) % P
                for k in range(r, len(rows)):
                    mat[j][k] = (mat[j][k] - factor * mat[pivot][k]) % P
    return rank


class Multiplication:
    """x . - as a map of bidegree (stem + d, filt + s0) on gr Ext.

    rank(n, s) returns the interval (lo, hi) of possible ranks, given that
    the table may not state every product.  zero=True is the split case: the
    connecting map of a split extension vanishes, so no table is consulted.
    """

    def __init__(self, cells, products, d, s0, zero=False):
        self.cells, self.products = cells, products
        self.d, self.s0, self.zero = d, s0, zero
        self.cache = {}

    def rank(self, n, s):
        if (n, s) in self.cache:
            return self.cache[(n, s)]
        source = self.cells.get((n, s), [])
        target = self.cells.get((n + self.d, s + self.s0), [])
        if self.zero or not source or not target:
            result = (0, 0)                        # zero map, or nowhere to land
        else:
            columns, unstated = [], 0
            for name in source:
                if name not in self.products:
                    unstated += 1
                    continue
                # a product landing on a differential-killed class is not a
                # class of E_infinity, so drop such terms rather than trust
                # the name
                columns.append(Counter({t: c for t, c
                                        in self.products[name].items()
                                        if t in target}))
            lo = f3_rank(columns, target)
            hi = min(lo + unstated, len(source), len(target))
            result = (lo, hi)
        self.cache[(n, s)] = result
        return result


def interval(lo, hi):
    return f'{lo}' if lo == hi else f'{lo}-{hi}'


# ------------------------------------------------------------- the check

def predict(cells, mult, n, s, top_shift):
    """Predicted interval for the length of E2(C_f) at (stem, filt) = (n, s).

    Bottom cell: coker of multiplication *into* (n, s).
    Top cell:    ker of multiplication *out of* (n - top_shift, s), landing in
                 stem n because Ext^{s,t}(Sigma^k BP_*) = Ext^{s,t-k}(BP_*).
    """
    bottom = len(cells.get((n, s), []))
    lo_in, hi_in = mult.rank(n - mult.d, s - mult.s0)

    top_cell = (n - top_shift, s)
    top = len(cells.get(top_cell, []))
    lo_out, hi_out = mult.rank(*top_cell)

    detail = dict(sphere=bottom, rank_in=(lo_in, hi_in),
                  coker=(bottom - hi_in, bottom - lo_in),
                  top_source=top, rank_out=(lo_out, hi_out),
                  ker=(top - hi_out, top - lo_out))
    return (bottom - hi_in + top - hi_out, bottom - lo_in + top - lo_out), detail


def main():
    ap = argparse.ArgumentParser(
        description='Check a two-cell mr_BP_comod run against the sphere E2 '
                    'page via the cofiber long exact sequence.',
        epilog='Run in the directory holding the finished runs.')
    ap.add_argument('halfT', help="the pipeline's first argument, e.g. 35")
    ap.add_argument('-c', '--comodule', default='alpha_1',
                    help='the mr_BP_comod comodule to check (default alpha_1)')
    ap.add_argument('-d', '--dir', default='.', help='where the tables live')
    ap.add_argument('-s', '--sphere', default=None,
                    help="prefix of the sphere run's tables (default: "
                         "<halfT>_sphereBP, falling back to <halfT>_BP)")
    ap.add_argument('--attaching', choices=['h0', 'none'], default='h0',
                    help='class detecting the attaching map: h0 = alpha_1 '
                         '(stem 3, filtration 1; the default), or none for a '
                         'split comodule such as triv_01')
    ap.add_argument('--top-cell', type=int, default=None,
                    help='dimension of the top cell (default 4 for h0, i.e. '
                         'the stem of alpha_1 plus one; 1 for --attaching none)')
    ap.add_argument('--max-t', type=int, default=None,
                    help='ignore bidegrees with t = stem + filt above this '
                         '(default: the largest t in the sphere run)')
    ap.add_argument('--max-filt', type=int, default=None,
                    help='ignore bidegrees above this filtration')
    ap.add_argument('-v', '--verbose', action='store_true',
                    help='show every bidegree in range, not just the '
                         'non-empty ones')
    a = ap.parse_args()

    top_shift = a.top_cell if a.top_cell is not None else (
        4 if a.attaching == 'h0' else 1)

    sphere_base = a.sphere
    if sphere_base is None:
        for candidate in (f'{a.halfT}_sphereBP', f'{a.halfT}_BP'):
            if os.path.exists(os.path.join(a.dir,
                                           candidate + 'AANSS_table.txt')):
                sphere_base = candidate
                break
    if sphere_base is None:
        sys.exit(f'error: no sphere run found in {a.dir}.\n'
                 f'Run ./mr_BP_comod {a.halfT} <s> sphere (or ./mr_BP) first.')
    sphere_base = os.path.join(a.dir, sphere_base)
    comod_base = os.path.join(a.dir, f'{a.halfT}_{a.comodule}BP')
    if not os.path.exists(comod_base + 'AANSS_table.txt'):
        sys.exit(f'error: {comod_base}AANSS_table.txt not found.\n'
                 f'Run ./mr_BP_comod {a.halfT} <s> {a.comodule} first.')

    sphere_cells = surviving(parse_table(sphere_base + 'AANSS_table.txt')[0])
    comod_cells = surviving(parse_table(comod_base + 'AANSS_table.txt')[0])

    if a.attaching == 'h0':
        products = parse_mult_coeffs(sphere_base + 'AANSS_h0.txt')
        if products is None:
            sys.exit(f'error: {sphere_base}AANSS_h0.txt not found.')
        mult = Multiplication(sphere_cells, products, d=3, s0=1)
    else:
        mult = Multiplication(sphere_cells, {}, d=0, s0=0, zero=True)

    max_t = a.max_t
    if max_t is None:
        max_t = max(n + s for (n, s) in sphere_cells)

    bidegrees = set(comod_cells)
    for (n, s) in sphere_cells:
        bidegrees.add((n, s))                       # bottom cell
        bidegrees.add((n + top_shift, s))           # top cell
    bidegrees = sorted(b for b in bidegrees
                       if b[0] + b[1] <= max_t
                       and (a.max_filt is None or b[1] <= a.max_filt))

    print(f'{a.comodule} vs sphere, halfT={a.halfT}, t <= {max_t}, '
          f'top cell in dimension {top_shift}')
    print('connecting map = multiplication by ' +
          ('alpha_1 = h0, of bidegree (stem +3, filtration +1)'
           if a.attaching == 'h0' else '0 (split extension)'))
    print()
    print(f'{"stem":>5} {"s":>3} | {"S":>4} {"rk_in":>6} {"coker":>6} | '
          f'{"S":>4} {"rk_out":>6} {"ker":>6} | {"pred":>6} {"obs":>4}  status')
    print('-' * 76)

    rows, agree, sharp, mismatch = [], 0, 0, []
    for (n, s) in bidegrees:
        (plo, phi), d = predict(sphere_cells, mult, n, s, top_shift)
        obs = len(comod_cells.get((n, s), []))
        if plo <= obs <= phi:
            status = 'ok' if plo == phi else 'ok (range)'
            agree += 1
            sharp += (plo == phi)
        else:
            status = 'MISMATCH'
            mismatch.append((n, s, (plo, phi), obs))
        # a predicted 0 where the sphere had a class is the most interesting
        # line on the page (that is a class the attaching map killed), so
        # show any bidegree either side has something to say about
        if a.verbose or plo or phi or obs or d['sphere'] or d['top_source']:
            print(f'{n:>5} {s:>3} | {d["sphere"]:>4} {interval(*d["rank_in"]):>6} '
                  f'{interval(*d["coker"]):>6} | {d["top_source"]:>4} '
                  f'{interval(*d["rank_out"]):>6} {interval(*d["ker"]):>6} | '
                  f'{interval(plo, phi):>6} {obs:>4}  {status}')

    print()
    print(f'{agree} bidegree(s) agree ({sharp} of them with the prediction '
          f'pinned down exactly), {len(mismatch)} mismatch(es).')
    for n, s, (plo, phi), obs in mismatch:
        print(f'  MISMATCH at (stem {n}, s={s}): predicted '
              f'{interval(plo, phi)}, observed {obs}')
    if mismatch:
        print('Before treating a mismatch as a wrong coaction, check the '
              'limitations in this script\'s docstring -- especially that '
              'multiplication tables record only the leading term of a '
              'product, and that the top of the range is cut off by the '
              'degree bound.')
    return 1 if mismatch else 0


if __name__ == '__main__':
    sys.exit(main())
